### ISSUE TITLE
not a function

### ISSUE THREAD

**Issue by TheSoulrester** [pupunzi/jquery.mb.YTPlayer#257]
```
jquery.min.js:2 jQuery.Deferred exception: jQuery(...).YTPlayer is not a function TypeError: jQuery(...).YTPlayer is not a function
    at HTMLDocument.<anonymous> (http://domain.tld/:611:20)
    at j (http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29588)
    at k (http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29902) undefined
```

getting this error
whats wrong? :D

**Comment by TheSoulrester** [comment]
ok...
realized it know with ```
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/css/jquery.mb.YTPlayer.min.css" media="all" rel="stylesheet" type="text/css">

<script data-relocate="true" src="http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script data-relocate="true" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.js"></script>
<script data-relocate="true" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.min.js"></script>
```

and this works fine for now
