### ISSUE TITLE
Video isn't starting because of an error

### ISSUE THREAD

**Issue by TheSoulrester** [pupunzi/jquery.mb.YTPlayer#274]
This is the Error in the console:

```
jQuery.Deferred exception: Unexpected token ; SyntaxError: Unexpected token ;
    at HTMLAnchorElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.min.js:8:2468)
    at Function.each (http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:2813)
    at r.fn.init.each (http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:1003)
    at r.fn.init.buildPlayer (https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.min.js:8:2080)
    at HTMLDocument.<anonymous> (http://domain.tld/:3915:22)
    at j (http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29588)
    at k (http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29902) undefined
```

and this is my sourcecode: 

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/css/jquery.mb.YTPlayer.min.css" media="all" rel="stylesheet" type="text/css">
 
<script data-relocate="true" src="http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script data-relocate="true" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.js"></script>
<script data-relocate="true" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.min.js"></script>

<a href="http://www.youtube.com/watch?v=w6OCl9WXz2I" id="bgndVideo" class="player" data-property="{ videoURL:'w6OCl9WXz2I', containment:'body', mute:false, showControls:false, ratio:'auto', quality:'default', opacity:1, optimizeDisplay:true, loop:true, vol:5; startAt:0, stopAt:0, remember_last_time:false, autoPlay:true, showYTLogo:false, addRaster:true, realfullscreen:false, stopMovieOnBlur:false, anchor:'center,center', showAnnotations:false }">Background Movie</a>
 
<script data-relocate="true" type="text/javascript">
    $(function() {
        $(".player").mb_YTPlayer();
    });
</script>
```

where is the issue?

**Comment by pupunzi** [comment]
Hi,
In your code you're including the javascript file twice. Just try removing one of them:

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/css/jquery.mb.YTPlayer.min.css" media="all">
 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.js"></script>

<a href="http://www.youtube.com/watch?v=w6OCl9WXz2I" id="bgndVideo" class="player" data-property="{ videoURL:'w6OCl9WXz2I', containment:'body', mute:false, showControls:false, ratio:'auto', quality:'default', opacity:1, optimizeDisplay:true, loop:true, vol:5; startAt:0, stopAt:0, remember_last_time:false, autoPlay:true, showYTLogo:false, addRaster:true, realfullscreen:false, stopMovieOnBlur:false, anchor:'center,center', showAnnotations:false }">Background Movie</a>
 
<script data-relocate="true" type="text/javascript">
    $(function() {
        $(".player").mb_YTPlayer();
    });
</script>
```

**Comment by TheSoulrester** [comment]
i think so! 
i'm using the woltlab software ([www.woltlab.com](url)) and they are including other javascript.

the funny thing is, that this code works fine?!  is the code which doesn't work.

```
{if $__wcf->getStyleHandler()->getStyle()->styleID == 36}
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/css/jquery.mb.YTPlayer.min.css" media="all" rel="stylesheet" type="text/css">
 
<script data-relocate="true" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.min.js"></script>

<!--<a href="http://www.youtube.com/watch?v=w6OCl9WXz2I" id="bgndVideo" class="player" data-property="{ videoURL:'w6OCl9WXz2I', containment:'body', mute:false, showControls:false, ratio:'auto', quality:'default', opacity:1, optimizeDisplay:true, loop:true, vol:0; startAt:0, stopAt:0, remember_last_time:false, autoPlay:true, showYTLogo:false, addRaster:true, realfullscreen:true, stopMovieOnBlur:false, anchor:'center,center', showAnnotations:false }">Background Movie</a>-->

<a href="http://www.youtube.com/watch?v=w6OCl9WXz2I" id="bgndVideo" class="player" data-property="{ videoURL:'w6OCl9WXz2I', containment:'body', startAt:0, showControls:false, autoPlay:true, loop:true, vol:0, mute:false, opacity:1, addRaster:true, quality:'default', ratio:'auto', optimizeDisplay:true, showYTLogo:false, stopMovieOnBlur:false, anchor:'center,center', showAnnotations:false }">Background Movie</a>
 
<script data-relocate="true" type="text/javascript">
    $(function() {
        $(".player").mb_YTPlayer();
    });
</script>
{/if}
```

this code is in a "template"-box. the template system works with "Smarty"

you can see that here: 
Working: [](http://natrix-esports.de/testvideobackground/)

**Comment by TheSoulrester** [comment]
http://natrix-esports.de/testvideobackground/

it isnt working - don't know why

**Comment by pupunzi** [comment]
Hi,
to start the video mute you have to set the "mute" property to true, if you set the vol to 0 it is not applied.

All the best,
Matteo

**Comment by TheSoulrester** [comment]
thx. 

and what about this error?:
```
Uncaught SyntaxError: Unexpected token ;
    at HTMLAnchorElement.<anonymous> (jquery.mb.YTPlayer.min.js:8)
    at Function.each (jquery.min.js:2)
    at r.fn.init.each (jquery.min.js:2)
    at r.fn.init.buildPlayer (jquery.mb.YTPlayer.min.js:8)
    at HTMLDocument.<anonymous> (natrix-esports.de/:1634)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```

do you have a solution?

**Comment by pupunzi** [comment]
Looking at the code of the test page you gave (http://natrix-esports.de/testvideobackground/) there's another javascript error that could be the cause of the issue:

Uncaught SyntaxError: missing ) after argument list

this error could break the rest of the javascript in the page.

**Comment by TheSoulrester** [comment]
hm... this wasn't the problem :(

```
jQuery.Deferred exception: Unexpected token ; SyntaxError: Unexpected token ;
    at HTMLAnchorElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.min.js:8:2468)
    at Function.each (http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:2815)
    at r.fn.init.each (http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:1003)
    at r.fn.init.buildPlayer (https://cdnjs.cloudflare.com/ajax/libs/jquery.mb.YTPlayer/3.0.19/jquery.mb.YTPlayer.min.js:8:2080)
    at HTMLDocument.<anonymous> (http://natrix-esports.de/testvideobackground/:1552:24)
    at j (http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:29948)
    at k (http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:30262) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
16:21:37.278 jquery.min.js:2 Uncaught SyntaxError: Unexpected token ;
    at HTMLAnchorElement.<anonymous> (jquery.mb.YTPlayer.min.js:8)
    at Function.each (jquery.min.js:2)
    at r.fn.init.each (jquery.min.js:2)
    at r.fn.init.buildPlayer (jquery.mb.YTPlayer.min.js:8)
    at HTMLDocument.<anonymous> (natrix-esports.de/:1552)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```

**Comment by TheSoulrester** [comment]
problem found. There was a ";" (semicolon) instead of a "," (comma)
