### ISSUE TITLE
Uncaught TypeError: YT.Player is not a constructor

### ISSUE THREAD

**Issue by luukee** [pupunzi/jquery.mb.YTPlayer#492]
Hello, wanted to see what this console error might be caused:

![Screen Shot 2022-11-21 at 11 22 18 AM](https://user-images.githubusercontent.com/30611098/203141246-dfc57ced-5cf2-449d-9e8c-4129a3f45ca5.png)

```
YTPlayer.min.js:1 Uncaught TypeError: YT.Player is not a constructor
    at HTMLDivElement.<anonymous> (YTPlayer.min.js:1:7803)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71659)
    at HTMLDivElement.<anonymous> (jquery.min.js:2:72254)
    at Function.each (jquery.min.js:2:3003)
    at s.fn.init.each (jquery.min.js:2:1481)
    at s.fn.init.trigger (jquery.min.js:2:72230)
    at YTPlayer.min.js:1:12708
```
You can see the error by visiting this page for example:

https://www.comedydynamics.com/catalog/drew-allen-out-of-ideas/

Thank you!
- Luke

**Comment by pupunzi** [comment]
Hi @luukee ,
The only error I get on your page is:
video ID:: xy9COCJjPOI: The video doesn't exist or The owner does not allow it to be played in embedded players

I can not reproduce the error you reported. Anyway, it could be caused by something that is blocking the embed of the Youtube API script loaded by The YTPlayer plugin.

**Comment by luukee** [comment]
Thanks for getting back @pupunzi. I was able to figure it out as it was an error in the theme I needed to fix.

Thanks again!
